# Generated by Django 5.1.4 on 2024-12-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='text',
        ),
    ]
